package proiectjava.dealershipfinalproject;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

public class CarTruckMotorcycleConditiiFrame extends javax.swing.JFrame {
    private final Car[] cars;
    DefaultListModel<Car> carDefaultListModel = new DefaultListModel<>();
    DefaultListModel<String> carListModel = new DefaultListModel<>();

    public CarTruckMotorcycleConditiiFrame() {
        initComponents();
        Engine carEngine1 = new Engine("V6", 200, 60, "Diesel");
        Engine carEngine2 = new Engine("V4", 120, 40, "Diesel");
        Engine carEngine3 = new Engine("V8", 300, 80, "Benzina");
        Engine carEngine4 = new Engine("V6", 300, 60, "Petrol");
        Engine carEngine5 = new Engine("V8", 450, 70, "Petrol");
        Engine carEngine6 = new Engine("Electric", 200, 100, "Electric");
        Engine carEngine7 = new Engine("V4", 180, 50, "Petrol");
        Engine carEngine8 = new Engine("Inline-6", 350, 65, "Diesel");
        Engine carEngine9 = new Engine("Hybrid", 250, 55, "Hybrid");
        Engine carEngine10 = new Engine("Boxer-4", 220, 45, "Petrol");
        
        Transmission carTransmission1 = new Transmission("Automatic", 6);
        Transmission carTransmission2 = new Transmission("Manual", 6);
        Transmission carTransmission3 = new Transmission("Automatic", 5);
        Transmission carTransmission4 = new Transmission("Automatic", 8);
        Transmission carTransmission5 = new Transmission("Manual", 6);
        Transmission carTransmission6 = new Transmission("CVT", 0);
        Transmission carTransmission7 = new Transmission("Automatic", 10);
        Transmission carTransmission8 = new Transmission("Manual", 5);
        Transmission carTransmission9 = new Transmission("Semi-Automatic", 7);
        Transmission carTransmission10 = new Transmission("Dual-Clutch", 9);
        
        this.cars = new Car[10];
        cars[0] = new Car(1, "Toyota", "Camry", (short) 2022, Color.BLUE, 25000.99, 1500, carEngine1, carTransmission1, null, 12000, 240, false, true, true, "Sedan");
        cars[1] = new Car(2, "Ford", "Mustang", (short) 2023, Color.RED, 45000.50, 1600, carEngine2, carTransmission2, null, 8000, 260, true, true, true, "Coupe");
        cars[2] = new Car(3, "Tesla", "Model S", (short) 2021, Color.WHITE, 75000.00, 2000, carEngine3, carTransmission3, null, 15000, 250, false, true, true, "Sedan");
        cars[3] = new Car(4, "Honda", "Civic", (short) 2020, Color.GRAY, 22000.00, 1300, carEngine4, carTransmission4, null, 18000, 220, false, true, false, "Hatchback");
        cars[4] = new Car(5, "BMW", "X5", (short) 2024, Color.BLACK, 60000.00, 2500, carEngine5, carTransmission5, null, 5000, 240, false, true, true, "SUV");
        cars[5] = new Car(6, "Toyota", "Prius", (short) 2022, Color.GREEN, 28000.00, 1400, carEngine6, carTransmission6, null, 10000, 180, false, true, true, "Hatchback");
        cars[6] = new Car(7, "Subaru", "Impreza", (short) 2021, Color.GREEN, 30000.00, 1450, carEngine7, carTransmission7, null, 15000, 220, false, true, true, "Sedan");
        cars[7] = new Car(8, "Lucid", "Air", (short) 2023, Color.RED, 80000.00, 2200, carEngine8, carTransmission8, null, 1200, 320, false, true, true, "Sedan");
        cars[8] = new Car(9, "Lamborghini", "Huracan", (short) 2023, Color.YELLOW, 200000.00, 1550, carEngine9, carTransmission9, null, 3000, 325, false, true, true, "Coupe");
        cars[9] = new Car(10, "Mazda", "RX-8", (short) 2009, Color.RED, 15000.00, 1300, carEngine10, carTransmission10, null, 50000, 230, true, true, false, "Coupe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        carPanel = new javax.swing.JPanel();
        carTitle = new javax.swing.JLabel();
        carLabel1 = new javax.swing.JLabel();
        carComboBox = new javax.swing.JComboBox<>();
        carLabel2 = new javax.swing.JLabel();
        carTextField = new javax.swing.JTextField();
        carScrollPane = new javax.swing.JScrollPane();
        carList = new javax.swing.JList<>();
        carProceedButton = new javax.swing.JButton();
        truckPanel = new javax.swing.JPanel();
        motorcyclePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 102, 102));
        mainPanel.setMaximumSize(new java.awt.Dimension(600, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 600));

        carPanel.setBackground(new java.awt.Color(216, 214, 196));
        carPanel.setMaximumSize(new java.awt.Dimension(99, 160));
        carPanel.setMinimumSize(new java.awt.Dimension(99, 160));
        carPanel.setPreferredSize(new java.awt.Dimension(99, 160));

        carTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        carTitle.setForeground(new java.awt.Color(0, 102, 102));
        carTitle.setText("Car");

        carLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        carLabel1.setForeground(new java.awt.Color(0, 102, 102));
        carLabel1.setText("Decapotabila:");

        carComboBox.setBackground(new java.awt.Color(0, 102, 102));
        carComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carComboBox.setForeground(new java.awt.Color(216, 214, 196));
        carComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));

        carLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        carLabel2.setForeground(new java.awt.Color(0, 102, 102));
        carLabel2.setText("Max. mileage:");

        carTextField.setBackground(new java.awt.Color(0, 102, 102));
        carTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carTextField.setForeground(new java.awt.Color(216, 214, 196));
        carTextField.setText("Enter mileage");

        carList.setBackground(new java.awt.Color(0, 102, 102));
        carList.setForeground(new java.awt.Color(216, 214, 196));
        carList.setModel(carListModel);
        carScrollPane.setViewportView(carList);

        carProceedButton.setBackground(new java.awt.Color(0, 102, 102));
        carProceedButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carProceedButton.setForeground(new java.awt.Color(216, 214, 196));
        carProceedButton.setText("Proceed");
        carProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carProceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carPanelLayout = new javax.swing.GroupLayout(carPanel);
        carPanel.setLayout(carPanelLayout);
        carPanelLayout.setHorizontalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carPanelLayout.createSequentialGroup()
                                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(carPanelLayout.createSequentialGroup()
                                        .addComponent(carLabel1)
                                        .addGap(31, 31, 31)
                                        .addComponent(carComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(carTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(carPanelLayout.createSequentialGroup()
                                .addComponent(carLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carProceedButton)))
                .addGap(18, 18, 18)
                .addComponent(carScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        carPanelLayout.setVerticalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addComponent(carTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carLabel1)
                            .addComponent(carComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carLabel2)
                            .addComponent(carTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carProceedButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout truckPanelLayout = new javax.swing.GroupLayout(truckPanel);
        truckPanel.setLayout(truckPanelLayout);
        truckPanelLayout.setHorizontalGroup(
            truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        truckPanelLayout.setVerticalGroup(
            truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout motorcyclePanelLayout = new javax.swing.GroupLayout(motorcyclePanel);
        motorcyclePanel.setLayout(motorcyclePanelLayout);
        motorcyclePanelLayout.setHorizontalGroup(
            motorcyclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        motorcyclePanelLayout.setVerticalGroup(
            motorcyclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motorcyclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(truckPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(carPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(truckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(motorcyclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carProceedButtonActionPerformed
        // TODO add your handling code here:
        String convertibleChoice = (String) carComboBox.getSelectedItem();
        Boolean convertibleChoiceBoolean = Boolean.parseBoolean(convertibleChoice);
        String mileageChoice = carTextField.getText();
        Integer mileageChoiceInteger = Integer.parseInt(mileageChoice);
        
        carDefaultListModel.clear(); // remove old elements for new generated state
        for(Car car : cars) {
            if(convertibleChoiceBoolean == car.isIsConvertible() && mileageChoiceInteger < car.getMileage()) {
                carDefaultListModel.addElement(car);
            }
        }
        
        carListModel.clear();
        for(int i = 0; i < carDefaultListModel.size(); i++) {
            Car car = carDefaultListModel.getElementAt(i);
            carListModel.addElement(car.toString());
        }
    }//GEN-LAST:event_carProceedButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarTruckMotorcycleConditiiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarTruckMotorcycleConditiiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarTruckMotorcycleConditiiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarTruckMotorcycleConditiiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarTruckMotorcycleConditiiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carComboBox;
    private javax.swing.JLabel carLabel1;
    private javax.swing.JLabel carLabel2;
    private javax.swing.JList<String> carList;
    private javax.swing.JPanel carPanel;
    private javax.swing.JButton carProceedButton;
    private javax.swing.JScrollPane carScrollPane;
    private javax.swing.JTextField carTextField;
    private javax.swing.JLabel carTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel motorcyclePanel;
    private javax.swing.JPanel truckPanel;
    // End of variables declaration//GEN-END:variables
}
