/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proiectjava.dealershipfinalproject;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 *
 * @author hcosm
 */
public class SearchBar extends javax.swing.JFrame {

    /**
     * Creates new form searchBar
     */
    public SearchBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vehicleSearchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleSearchResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        vehicleSearchBar.setBackground(new java.awt.Color(216, 214, 196));
        vehicleSearchBar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vehicleSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleSearchBarActionPerformed(evt);
            }
        });
        vehicleSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehicleSearchBarKeyTyped(evt);
            }
        });

        vehicleSearchResult.setBackground(new java.awt.Color(216, 214, 196));
        vehicleSearchResult.setColumns(20);
        vehicleSearchResult.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vehicleSearchResult.setRows(5);
        jScrollPane1.setViewportView(vehicleSearchResult);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addComponent(vehicleSearchBar))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(vehicleSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSearchBarActionPerformed
        
    }//GEN-LAST:event_vehicleSearchBarActionPerformed

    private void vehicleSearchBarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehicleSearchBarKeyTyped
 String finalstring = "";
        File file = new File("");
                 String filePath = "availableVehicles.txt"; // Replace with the path to your file 
            try (Stream<String> lines = Files.lines(Paths.get(filePath))) {
                
                List<String> randomLines = lines
                        .collect(Collectors.toList());
                for (String line : randomLines) {
                    String splitline[]=line.split(",");
                    
                    if(vehicleSearchBar.getText().equals(splitline[0])||vehicleSearchBar.getText().equals(splitline[2])||vehicleSearchBar.getText().equals(splitline[3])
                            ||vehicleSearchBar.getText().toLowerCase().equals(splitline[0].toLowerCase())||vehicleSearchBar.getText().toLowerCase().equals(splitline[2].toLowerCase())||vehicleSearchBar.getText().toLowerCase().equals(splitline[3].toLowerCase())
                            
                            )
                    {
                       finalstring+=line+"\n";
                    }
                }
                //get nr of lines
            } catch (IOException e) {
                System.err.println("Error reading purchases.txt: " + e.getMessage());
               
            }
             vehicleSearchResult.setText(finalstring);
 
    }//GEN-LAST:event_vehicleSearchBarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBar().setVisible(true);
            }
        });
    }
    
   private String chooser() {

        String finalstring = "";
        File file = new File("");

        {
            String filePath = "availableVehicles.txt"; // Replace with the path to your file 
            try (Stream<String> lines = Files.lines(Paths.get(filePath))) {
 
                List<String> randomLines = lines
                        .collect(Collectors.toList());
                for (String line : randomLines) {
                    finalstring += line +"/";
                }
                //get nr of lines
            } catch (IOException e) {
                System.err.println("Error reading purchases.txt: " + e.getMessage());
                return "";
            }
        }
        return finalstring;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField vehicleSearchBar;
    private javax.swing.JTextArea vehicleSearchResult;
    // End of variables declaration//GEN-END:variables
}
